FROM ubuntu:19.10

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update
RUN apt dist-upgrade -y
RUN apt install -y libmariadb3 libssl libreadline5 zlib1g \
    libncurses5 libbz2-1.0 libpthread-workqueue0 libace-6.4.5 pkg-config \
    mariadb-client gdb

ADD bin/worldserver /tc/bin/worldserver
ADD bin/worldserver.dbg /tc/bin/worldserver.dbg

WORKDIR /tc/bin

VOLUME ["/tc/core"]
CMD ["gdb", "--symbols=/tc/bin/worldserver.dbg", "--core=/tc/core/core.worldserver", "--exec=/tc/bin/worldserver"]
