FROM ubuntu:19.10

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update
RUN apt dist-upgrade -y
RUN apt install -y libmariadb3 libssl1.1 libreadline5 zlib1g \
    libncurses5 libbz2-1.0 libpthread-workqueue0 pkg-config \
    mariadb-client libboost-system1.67.0 libboost-filesystem1.67.0 \
    libboost-thread1.67.0 libboost-program-options1.67.0 \
    libboost-iostreams1.67.0 gdb

ADD bin/worldserver /tc/bin/worldserver

WORKDIR /tc/bin

VOLUME ["/tc/core"]
CMD ["gdb", "/tc/bin/worldserver", "/tc/core/core.worldserver"]
