FROM debian:buster

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update
# RUN apt dist-upgrade -y
RUN apt install -y libmariadbclient-dev libssl-dev libreadline5 zlib1g \
    libncurses5 libbz2-1.0 libace-dev pkg-config \
    libace-dev mariadb-client python3 python3-pip supervisor net-tools \
    default-libmysqlclient-dev libboost-all-dev
RUN pip3 install flask gunicorn

RUN mkdir -p /tc/logs
RUN mkdir -p /tc/data
RUN mkdir -p /tc/bin

ADD bin/worldserver /tc/bin
ADD scripts/misc/world_metrics.py /tc/bin
ADD image/supervisord.conf /tc/supervisord.conf

WORKDIR /tc/bin

EXPOSE 8080 8085 7878
VOLUME ["/tc/logs", "/tc/data", "/tc/etc"]
CMD ["supervisord", "-c", "/tc/supervisord.conf", "-n"]
